"""
statistical_tests.py
────────────────────
Statistical analysis of the results from `train_kfold.py`.

What it computes
----------------
1) 95% CI of the mean AUC per (model, muscle) with two methods:
     - Student's t over the 5 per-fold AUCs  (primary)
     - bootstrap (N=1000) over the 5 AUCs    (complementary, non-parametric)
   Note: bootstrap over concatenated predictions is NOT used because each
   fold comes from a different model with its own calibration, and mixing
   their probabilities degrades the global ranking.
2) Comparison vs. the clinical baseline of Martinez-Paya 2017:
   - If the published AUC falls OUTSIDE the t-Student 95% CI, we declare a
     "statistically significant difference" (p<0.05).
   - If it falls INSIDE, the result is "equivalent / inconclusive".
3) Clinical metrics recalibrated with Youden's J:
   - Search for the optimal per-fold threshold that maximises Sens+Spec-1.
   - Comparison against the fixed 0.5 threshold used by the model by default.
4) Paired comparison between architectures within the same muscle:
   - Wilcoxon signed-rank test over the 5 per-fold AUCs (paired).
   - DeLong test over concatenated predictions (real ROC).
   - McNemar test over binary hits/misses.

Input
-----
`models/resultados_kfold/kfold_predictions.json` (generated by train_kfold.py)

Output
------
- models/resultados_kfold/ci_bootstrap.csv           (CI95% per model/muscle)
- models/resultados_kfold/vs_baseline.csv            (comparison with Martinez-Paya)
- models/resultados_kfold/recalibrated_youden.csv    (Sens/Spec at optimal threshold)
- models/resultados_kfold/pairwise_models.csv        (tests between architectures)
- models/resultados_kfold/plots/boxplot_auc_{muscle}.png
- models/resultados_kfold/informe_estadistico.txt

Usage
-----
    cd src
    python3 statistical_tests.py
"""
import os
import json
import csv
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from itertools import combinations

from sklearn.metrics import roc_auc_score
from scipy import stats
from statsmodels.stats.contingency_tables import mcnemar

from config import Config


# ── Constants ──────────────────────────────────────────────────────────
RESULTS_DIR = os.path.join(Config.BASE_DIR, "models", "resultados_kfold")
PRED_PATH   = os.path.join(RESULTS_DIR, "kfold_predictions.json")
PLOTS_DIR   = os.path.join(RESULTS_DIR, "plots")

# Published baseline (Martinez-Paya 2017). AUC in percent.
BASELINE = {
    "Bicep":      {"auc": 92.6, "sens": 88.0, "spec": 83.0, "tech": "EV+MTh"},
    "Antebrazo":  {"auc": 90.5, "sens": 81.0, "spec": 79.0, "tech": "GLCM+MTh"},
    "Quadriceps": {"auc": 98.3, "sens": 94.0, "spec": 96.0, "tech": "GLCM+MTh"},
    "Tibial":     {"auc": 95.3, "sens": 85.0, "spec": 92.0, "tech": "EV+MTh"},
}

N_BOOTSTRAP = 1000
RNG_SEED    = Config.SEED


# ── Data loading ───────────────────────────────────────────────────────
def load_predictions():
    if not os.path.exists(PRED_PATH):
        raise FileNotFoundError(
            f"Cannot find {PRED_PATH}. Run `python3 train_kfold.py` first."
        )
    with open(PRED_PATH) as f:
        data = json.load(f)
    # Group by (model, muscle)
    grouped = {}
    for r in data:
        key = (r["model"], r["muscle"])
        grouped.setdefault(key, []).append(r)
    return grouped


def _concat_predictions(folds):
    """Concatenates y_true, y_probs, y_pred of the 5 folds into a single vector."""
    y_true  = np.array([y for f in folds for y in f["y_true"]])
    y_pred  = np.array([y for f in folds for y in f["y_pred"]])
    y_probs = np.array([p for f in folds for p in f["y_probs"]])
    return y_true, y_pred, y_probs


# ── 1. Confidence interval of the mean per-fold AUC ───────────────────
# Methodological note: the "concatenation" bootstrap (resampling over the
# merged predictions of the 5 folds) is incorrect when each fold comes from
# a different model with its own probability calibration, because mixing
# probabilities from different models artificially degrades the global
# ranking and the CI collapses.
# The correct approach for k-fold CV with small n is the Student CI over the
# k per-fold AUCs: mean ± t(n-1, α/2) · std / √n .
# We complement it with a bootstrap *of the per-fold AUCs themselves*
# (resampling the 5 values with replacement) to also have a non-parametric CI.
def auc_ci_from_folds(fold_aucs, alpha=0.05, n_boot=N_BOOTSTRAP):
    """
    CI for the mean AUC over the k folds.
    Returns: (mean, t_low, t_high, boot_low, boot_high) in percent.
    """
    arr = np.asarray(fold_aucs, dtype=float)
    n = len(arr)
    mean = float(arr.mean())
    # Student t CI (primary)
    if n > 1:
        std = float(arr.std(ddof=1))
        t_crit = float(stats.t.ppf(1 - alpha / 2, df=n - 1))
        half = t_crit * std / np.sqrt(n)
    else:
        half = 0.0
    t_low  = max(0.0, mean - half)
    t_high = min(100.0, mean + half)
    # Bootstrap CI over the k AUCs (secondary, non-parametric)
    rng = np.random.default_rng(RNG_SEED)
    means = np.array([arr[rng.integers(0, n, n)].mean() for _ in range(n_boot)])
    b_low  = float(np.quantile(means, alpha / 2))
    b_high = float(np.quantile(means, 1 - alpha / 2))
    return mean, t_low, t_high, b_low, b_high


def run_ci_per_model_muscle(grouped):
    rows = []
    for (model, muscle), folds in grouped.items():
        per_fold_auc = [f["auc"] for f in folds]   # already in percent
        mean, t_low, t_high, b_low, b_high = auc_ci_from_folds(per_fold_auc)
        rows.append({
            "model":    model,
            "muscle":   muscle,
            "n_folds":  len(folds),
            "auc_fold_mean":  round(mean,   2),
            "auc_fold_std":   round(float(np.std(per_fold_auc, ddof=1)), 2),
            "auc_t_ci_low":   round(t_low,  2),
            "auc_t_ci_high":  round(t_high, 2),
            "auc_boot_ci_low":  round(b_low,  2),
            "auc_boot_ci_high": round(b_high, 2),
        })
    rows.sort(key=lambda r: (r["muscle"], -r["auc_fold_mean"]))
    _write_csv(os.path.join(RESULTS_DIR, "ci_bootstrap.csv"), rows)
    return rows


# ── 2. Comparison vs baseline ──────────────────────────────────────────
def compare_vs_baseline(ci_rows):
    """
    For each (model, muscle): does the baseline AUC fall INSIDE or OUTSIDE
    our model's 95% CI (t-Student)? If outside and above -> the baseline is
    better. If outside and below -> our model is better.

    We use the t-Student CI as the primary one (appropriate for the mean of
    k per-fold AUCs with k=5). The bootstrap CI is kept as a complement.
    """
    rows = []
    for r in ci_rows:
        base = BASELINE[r["muscle"]]["auc"]
        low, high = r["auc_t_ci_low"], r["auc_t_ci_high"]
        if base < low:
            verdict = "NUESTRO MEJOR (p<0.05)"
        elif base > high:
            verdict = "BASELINE MEJOR (p<0.05)"
        else:
            verdict = "equivalente / no concluyente"
        rows.append({
            "model":            r["model"],
            "muscle":           r["muscle"],
            "our_auc":          r["auc_fold_mean"],
            "our_t_ci_low":     r["auc_t_ci_low"],
            "our_t_ci_high":    r["auc_t_ci_high"],
            "our_boot_ci_low":  r["auc_boot_ci_low"],
            "our_boot_ci_high": r["auc_boot_ci_high"],
            "baseline_auc":     base,
            "baseline_tech":    BASELINE[r["muscle"]]["tech"],
            "verdict":          verdict,
        })
    rows.sort(key=lambda r: (r["muscle"], -r["our_auc"]))
    _write_csv(os.path.join(RESULTS_DIR, "vs_baseline.csv"), rows)
    return rows


# ── 2b. Clinical recalibration with Youden's J per fold ────────────────
# The model is saved with a 0.5 threshold, which is not optimal if the
# classes are imbalanced or the model is poorly calibrated. To report
# honest Sens/Spec, we search in EACH fold for the threshold that maximises
# Youden's index J = Sens + Spec - 1 over its own predictions, and we
# average the resulting metrics across folds.
def _metrics_at_threshold(y_true, y_probs, thr):
    y_pred = (np.asarray(y_probs) >= thr).astype(int)
    y_true = np.asarray(y_true)
    tp = int(np.sum((y_pred == 1) & (y_true == 1)))
    tn = int(np.sum((y_pred == 0) & (y_true == 0)))
    fp = int(np.sum((y_pred == 1) & (y_true == 0)))
    fn = int(np.sum((y_pred == 0) & (y_true == 1)))
    sens = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    spec = tn / (tn + fp) if (tn + fp) > 0 else 0.0
    acc  = (tp + tn) / max(1, (tp + tn + fp + fn))
    return sens * 100, spec * 100, acc * 100


def _best_youden_threshold(y_true, y_probs):
    """Finds the threshold that maximises Sens+Spec-1 sweeping the unique probs."""
    y_true  = np.asarray(y_true)
    y_probs = np.asarray(y_probs)
    # Include 0 and 1 for the extremes; candidate points = the probs themselves
    cand = np.unique(np.concatenate([[0.0, 1.0], y_probs]))
    best = (-1.0, 0.5, 0.0, 0.0)  # J, thr, sens, spec
    for t in cand:
        s, sp, _ = _metrics_at_threshold(y_true, y_probs, t)
        j = (s + sp) / 100 - 1
        if j > best[0]:
            best = (j, float(t), s, sp)
    return best  # (J, thr, sens, spec)


def run_recalibrated_metrics(grouped):
    """
    For each (model, muscle), recalibrates Sens/Spec/Acc per fold using
    Youden's J, and returns the mean ± std across folds.
    """
    rows = []
    for (model, muscle), folds in grouped.items():
        sens_l, spec_l, acc_l, thr_l = [], [], [], []
        sens05_l, spec05_l = [], []
        for f in folds:
            yt, yp, pp = f["y_true"], f["y_pred"], f["y_probs"]
            # Youden per fold over ITS own probs (local calibration)
            _, thr, s, sp = _best_youden_threshold(yt, pp)
            s05, sp05, acc05 = _metrics_at_threshold(yt, pp, 0.5)
            _, _, accJ = _metrics_at_threshold(yt, pp, thr)
            sens_l.append(s);   spec_l.append(sp);   acc_l.append(accJ); thr_l.append(thr)
            sens05_l.append(s05); spec05_l.append(sp05)
        rows.append({
            "model":             model,
            "muscle":            muscle,
            "n_folds":           len(folds),
            # 0.5 threshold (the one the model uses as is)
            "sens_thr05_mean":   round(float(np.mean(sens05_l)), 2),
            "spec_thr05_mean":   round(float(np.mean(spec05_l)), 2),
            # Youden's J
            "sens_youden_mean":  round(float(np.mean(sens_l)), 2),
            "sens_youden_std":   round(float(np.std(sens_l, ddof=1)) if len(sens_l) > 1 else 0.0, 2),
            "spec_youden_mean":  round(float(np.mean(spec_l)), 2),
            "spec_youden_std":   round(float(np.std(spec_l, ddof=1)) if len(spec_l) > 1 else 0.0, 2),
            "acc_youden_mean":   round(float(np.mean(acc_l)), 2),
            "thr_youden_mean":   round(float(np.mean(thr_l)), 3),
            "thr_youden_std":    round(float(np.std(thr_l, ddof=1)) if len(thr_l) > 1 else 0.0, 3),
        })
    rows.sort(key=lambda r: (r["muscle"], -r["acc_youden_mean"]))
    _write_csv(os.path.join(RESULTS_DIR, "recalibrated_youden.csv"), rows)
    return rows


# ── 3a. Paired tests between architectures ─────────────────────────────
def _wilcoxon_auc(folds_a, folds_b):
    """Paired test over per-fold AUC (same StratifiedGroupKFold partition)."""
    auc_a = [f["auc"] for f in sorted(folds_a, key=lambda r: r["fold"])]
    auc_b = [f["auc"] for f in sorted(folds_b, key=lambda r: r["fold"])]
    if len(auc_a) != len(auc_b):
        return None, None
    try:
        stat, p = stats.wilcoxon(auc_a, auc_b)
        return float(stat), float(p)
    except ValueError:
        return None, None  # all folds equal


def _delong_test(y_true, probs_a, probs_b):
    """
    DeLong test to compare two correlated AUCs (same y_true).
    Implementation based on Sun & Xu (2014), O(n log n). Returns (z, p).
    """
    y_true   = np.asarray(y_true)
    probs_a  = np.asarray(probs_a)
    probs_b  = np.asarray(probs_b)

    pos = y_true == 1
    neg = y_true == 0
    xa, ya = probs_a[pos], probs_a[neg]
    xb, yb = probs_b[pos], probs_b[neg]
    m, n = len(xa), len(ya)
    if m == 0 or n == 0:
        return None, None

    # V components (placement values)
    def placement(x, y):
        v10 = np.array([(np.sum(y < xi) + 0.5 * np.sum(y == xi)) / len(y) for xi in x])
        v01 = np.array([(np.sum(x > yj) + 0.5 * np.sum(x == yj)) / len(x) for yj in y])
        return v10, v01

    v10_a, v01_a = placement(xa, ya)
    v10_b, v01_b = placement(xb, yb)

    auc_a = v10_a.mean()
    auc_b = v10_b.mean()

    # 2x2 covariance matrix between the two AUCs
    s10 = np.cov(np.vstack([v10_a, v10_b])) / m
    s01 = np.cov(np.vstack([v01_a, v01_b])) / n
    S = s10 + s01

    var_diff = S[0, 0] + S[1, 1] - 2 * S[0, 1]
    if var_diff <= 0:
        return 0.0, 1.0
    z = (auc_a - auc_b) / np.sqrt(var_diff)
    p = 2 * (1 - stats.norm.cdf(abs(z)))
    return float(z), float(p)


def _mcnemar_test(y_true, pred_a, pred_b):
    """McNemar test over binary hits/misses."""
    y_true = np.asarray(y_true)
    pred_a = np.asarray(pred_a)
    pred_b = np.asarray(pred_b)
    correct_a = pred_a == y_true
    correct_b = pred_b == y_true
    b01 = int(np.sum( correct_a & ~correct_b))  # A right, B wrong
    b10 = int(np.sum(~correct_a &  correct_b))  # A wrong, B right
    table = [[0, b01], [b10, 0]]
    try:
        res = mcnemar(table, exact=True)
        return float(res.statistic), float(res.pvalue), b01, b10
    except Exception:
        return None, None, b01, b10


def run_pairwise_between_models(grouped):
    rows = []
    muscles = sorted({m for (_, m) in grouped.keys()})

    for muscle in muscles:
        combos = sorted([(mn, folds) for (mn, mu), folds in grouped.items()
                         if mu == muscle])
        for (mn_a, folds_a), (mn_b, folds_b) in combinations(combos, 2):
            ya, pa, ppa = _concat_predictions(folds_a)
            yb, pb, ppb = _concat_predictions(folds_b)
            # Sanity: same y_true (same StratifiedGroupKFold partition)
            same_y = (len(ya) == len(yb) and np.array_equal(ya, yb))

            w_stat, w_p = _wilcoxon_auc(folds_a, folds_b)
            if same_y:
                d_z, d_p                  = _delong_test(ya, ppa, ppb)
                m_stat, m_p, b01, b10     = _mcnemar_test(ya, pa, pb)
            else:
                d_z = d_p = m_stat = m_p = None
                b01 = b10 = None

            rows.append({
                "muscle":       muscle,
                "model_a":      mn_a,
                "model_b":      mn_b,
                "auc_a_mean":   round(float(np.mean([f['auc'] for f in folds_a])), 2),
                "auc_b_mean":   round(float(np.mean([f['auc'] for f in folds_b])), 2),
                "wilcoxon_p":   _round(w_p),
                "delong_p":     _round(d_p),
                "mcnemar_p":    _round(m_p),
                "mcnemar_b01":  b01,
                "mcnemar_b10":  b10,
            })
    rows.sort(key=lambda r: (r["muscle"],
                             r["wilcoxon_p"] if r["wilcoxon_p"] is not None else 1))
    _write_csv(os.path.join(RESULTS_DIR, "pairwise_models.csv"), rows)
    return rows


# ── 4. AUC boxplots per muscle ─────────────────────────────────────────
def plot_boxplots_per_muscle(grouped):
    os.makedirs(PLOTS_DIR, exist_ok=True)
    muscles = sorted({m for (_, m) in grouped.keys()})
    for muscle in muscles:
        combos = sorted([(mn, folds) for (mn, mu), folds in grouped.items()
                         if mu == muscle])
        if not combos:
            continue
        names = [mn for mn, _ in combos]
        aucs  = [[f["auc"] for f in folds] for _, folds in combos]

        fig, ax = plt.subplots(figsize=(10, 5.5))
        bp = ax.boxplot(aucs, labels=[n.upper() for n in names],
                        patch_artist=True, showmeans=True,
                        meanprops=dict(marker="D", markerfacecolor="white",
                                       markeredgecolor="black"))
        # Horizontal baseline
        ax.axhline(BASELINE[muscle]["auc"], color="red", linestyle="--",
                   linewidth=1.2,
                   label=f"Baseline Martinez-Paya 2017: {BASELINE[muscle]['auc']}%")
        # Colors
        cmap = plt.cm.tab10(np.linspace(0, 1, len(names)))
        for patch, color in zip(bp["boxes"], cmap):
            patch.set_facecolor(color)
            patch.set_alpha(0.5)

        ax.set_ylabel("AUC (%)")
        ax.set_title(f"AUC per fold — {muscle} (5-fold StratifiedGroupKFold)")
        ax.set_ylim(40, 105)
        ax.grid(axis="y", alpha=0.3)
        ax.legend(loc="lower right", fontsize=9)
        plt.xticks(rotation=20)
        plt.tight_layout()
        path = os.path.join(PLOTS_DIR, f"boxplot_auc_{muscle.lower()}.png")
        plt.savefig(path, dpi=150)
        plt.close()
        print(f"  Boxplot -> {path}")


# ── 5. Human-readable final report (kept in Spanish: it ships with the
#       Spanish thesis as a results artifact) ──────────────────────────
def write_report(ci_rows, vs_base_rows, pairwise_rows, recal_rows):
    path = os.path.join(RESULTS_DIR, "informe_estadistico.txt")
    with open(path, "w") as f:
        f.write("="*78 + "\n")
        f.write("  INFORME ESTADÍSTICO — TFG ELA (5-fold StratifiedGroupKFold)\n")
        f.write("="*78 + "\n\n")

        f.write("1) AUC MEDIO POR (MODELO, MÚSCULO) CON IC 95 %\n")
        f.write("   IC principal: t-Student sobre los 5 AUCs por fold.\n")
        f.write("   IC secundario: bootstrap (N=1000) sobre los 5 AUCs.\n")
        f.write("-"*78 + "\n")
        for muscle in ["Bicep", "Antebrazo", "Quadriceps", "Tibial"]:
            f.write(f"\n  -- {muscle.upper()} --\n")
            f.write(f"  {'MODEL':<18} {'AUC fold μ±σ':<18} "
                    f"{'IC95% t-Stud':<22} {'IC95% boot':<22}\n")
            f.write("  " + "-"*78 + "\n")
            subset = [r for r in ci_rows if r["muscle"] == muscle]
            for r in subset:
                f.write(f"  {r['model']:<18} "
                        f"{r['auc_fold_mean']:>6.2f} ± {r['auc_fold_std']:<6.2f}  "
                        f"[{r['auc_t_ci_low']:>5.2f}; {r['auc_t_ci_high']:>5.2f}]   "
                        f"[{r['auc_boot_ci_low']:>5.2f}; {r['auc_boot_ci_high']:>5.2f}]\n")

        f.write("\n\n2) COMPARACIÓN VS MARTÍNEZ-PAYÁ 2017 (IC t-Student)\n")
        f.write("-"*78 + "\n")
        for muscle in ["Bicep", "Antebrazo", "Quadriceps", "Tibial"]:
            base = BASELINE[muscle]
            f.write(f"\n  -- {muscle.upper()} --  "
                    f"baseline AUC={base['auc']}% ({base['tech']})\n")
            subset = [r for r in vs_base_rows if r["muscle"] == muscle]
            for r in subset:
                f.write(f"    {r['model']:<18} "
                        f"AUC={r['our_auc']:>6.2f}% "
                        f"[{r['our_t_ci_low']:>5.2f}, {r['our_t_ci_high']:>5.2f}]  "
                        f"-> {r['verdict']}\n")

        f.write("\n\n3) MÉTRICAS CLÍNICAS RECALIBRADAS (umbral óptimo de Youden's J)\n")
        f.write("    Comparar Sens/Spec a umbral fijo 0.5 vs. umbral óptimo por fold.\n")
        f.write("-"*78 + "\n")
        for muscle in ["Bicep", "Antebrazo", "Quadriceps", "Tibial"]:
            f.write(f"\n  -- {muscle.upper()} --  "
                    f"(baseline Sens={BASELINE[muscle]['sens']}%, "
                    f"Spec={BASELINE[muscle]['spec']}%)\n")
            f.write(f"  {'MODEL':<18} {'Sens@0.5':>9} {'Spec@0.5':>9} "
                    f"{'Sens@J':>10} {'Spec@J':>10} {'Acc@J':>8} {'thr@J':>8}\n")
            f.write("  " + "-"*78 + "\n")
            subset = [r for r in recal_rows if r["muscle"] == muscle]
            for r in subset:
                f.write(f"  {r['model']:<18} "
                        f"{r['sens_thr05_mean']:>8.2f}% "
                        f"{r['spec_thr05_mean']:>8.2f}%  "
                        f"{r['sens_youden_mean']:>7.2f}±{r['sens_youden_std']:<4.1f}  "
                        f"{r['spec_youden_mean']:>7.2f}±{r['spec_youden_std']:<4.1f}  "
                        f"{r['acc_youden_mean']:>6.2f}% "
                        f"{r['thr_youden_mean']:>6.3f}\n")

        f.write("\n\n4) COMPARACIÓN PAREADA ENTRE ARQUITECTURAS\n")
        f.write("    (por músculo; p<0.05 indica diferencia significativa)\n")
        f.write("-"*78 + "\n")
        for muscle in ["Bicep", "Antebrazo", "Quadriceps", "Tibial"]:
            f.write(f"\n  -- {muscle.upper()} --\n")
            f.write(f"  {'A':<18} {'B':<18} "
                    f"{'Wilcoxon p':>12} {'DeLong p':>12} {'McNemar p':>12}\n")
            f.write("  " + "-"*72 + "\n")
            subset = [r for r in pairwise_rows if r["muscle"] == muscle]
            for r in subset:
                f.write(f"  {r['model_a']:<18} {r['model_b']:<18} "
                        f"{_fmt_p(r['wilcoxon_p']):>12} "
                        f"{_fmt_p(r['delong_p']):>12} "
                        f"{_fmt_p(r['mcnemar_p']):>12}\n")

        f.write("\n\nNotas metodológicas:\n")
        f.write("- IC t-Student sobre los 5 AUCs por fold es el método estándar en\n")
        f.write("  k-fold CV con k pequeño. El bootstrap sobre predicciones concatenadas\n")
        f.write("  NO es válido aquí porque cada fold viene de un modelo distinto con su\n")
        f.write("  propia calibración de probabilidades.\n")
        f.write("- 'Wilcoxon p' es un test pareado sobre los 5 AUCs por fold.\n")
        f.write("- 'DeLong p' es un test sobre los AUCs agregados (predicciones concatenadas).\n")
        f.write("- 'McNemar p' compara aciertos/fallos binarios sobre predicciones concatenadas.\n")
        f.write("- El umbral de Youden (J = Sens+Spec-1) se busca en CADA fold sobre sus\n")
        f.write("  propias probabilidades. Las métricas reportadas son la media entre folds.\n")
        f.write("- Frente al baseline de Martínez-Payá no podemos aplicar DeLong/McNemar\n")
        f.write("  porque no están disponibles sus predicciones individuales, por eso\n")
        f.write("  usamos el IC t-Student del AUC y verificamos si el valor publicado cae\n")
        f.write("  dentro del intervalo.\n")
    print(f"  Report -> {path}")


# ── Utilities ──────────────────────────────────────────────────────────
def _round(x, n=4):
    return None if x is None else round(x, n)


def _fmt_p(p):
    if p is None:
        return "n/a"
    if p < 0.001:
        return "<0.001 ***"
    if p < 0.01:
        return f"{p:.3f} **"
    if p < 0.05:
        return f"{p:.3f} *"
    return f"{p:.3f}"


def _write_csv(path, rows):
    if not rows:
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        for r in rows:
            writer.writerow(r)
    print(f"  CSV -> {path}")


# ── Main ───────────────────────────────────────────────────────────────
def main():
    os.makedirs(RESULTS_DIR, exist_ok=True)
    print(f"Loading predictions from: {PRED_PATH}")
    grouped = load_predictions()
    n_combos = len(grouped)
    print(f"Combinations (model x muscle): {n_combos}")

    print("\n[1/5] AUC 95% CI (t-Student + bootstrap over folds)...")
    ci_rows = run_ci_per_model_muscle(grouped)

    print("\n[2/5] Comparison vs Martinez-Paya 2017...")
    vs_rows = compare_vs_baseline(ci_rows)

    print("\n[3/5] Sens/Spec recalibration with Youden's J...")
    recal_rows = run_recalibrated_metrics(grouped)

    print("\n[4/5] Paired tests between architectures...")
    pairwise_rows = run_pairwise_between_models(grouped)

    print("\n[5/5] Boxplots and final report...")
    plot_boxplots_per_muscle(grouped)
    write_report(ci_rows, vs_rows, pairwise_rows, recal_rows)

    print("\nDone. Results in:", RESULTS_DIR)


if __name__ == "__main__":
    main()
